### ISSUE TITLE
很需要的功能，只是我打开html文件后显示空白的。

### ISSUE THREAD

**Issue by xtvj** [KyleBing/wubi-dict-editor#1]
如何使用？直接用浏览器打开index.html文件？但我尝试用chrome或firefox打开都显示空白，MacOS11.5.1

**Comment by KyleBing** [comment]
这是原文件，需要编译，目前还没做好基础功能，先不提供可执行文件。等把基础的功能弄的差不多了再把可执行文件放出来。

**Comment by xtvj** [comment]
了解了，希望早点推出，十分需要的功能，谢谢！！

**Comment by KyleBing** [comment]
macOS 的话，如果你使用的是我建的那个配置文件，可以使用 [https://github.com/KyleBing/WubiBuddy](https://github.com/KyleBing/WubiBuddy) 这个工具，如果是其它库，那暂时用不了，之前那个工具局限性很强，只认一个文件。

**Comment by xtvj** [comment]
由于操作习惯的问题，我习惯输入时已有输入内容时输入[。]变成[.]并且不上屏，按空格或是回车上屏英文（官方操作逻辑），您的配置是上屏中文加上[。]

之前在那还提过[Issues](https://github.com/KyleBing/rime-wubi86-jidian/issues/49)，用您的配置不到半个月就好几次输网址时不适应就换回官方配置了，只是官网词库实在太少，我五笔和汉语都是个半吊子，想不起来字怎么写或是成语里是用哪个汉字时就用五笔拼音里的拼音混输的。

在网上找了词库转换的工具，转换显示成功了，但部署后都没用。

如果您这个工具有**批量添加词条功能**就更好了，说实话随便找两个词库加起来就能满足99.9%的需求，日常单个添加词条的操作对于像我这样要求不高的人来说就用的少了。

**Comment by KyleBing** [comment]
欢迎试用最新版
[https://github.com/KyleBing/wubi-dict-editor/releases/tag/v1.01beta2](https://github.com/KyleBing/wubi-dict-editor/releases/tag/v1.01beta2)
