### ISSUE TITLE
打开词库编辑工具看不到词库内容

### ISSUE THREAD

**Issue by chengyi** [KyleBing/wubi-dict-editor#12]
下载了你的配置之后，用这个配套的工具，无法读取词库内容，词库窗口空白

**Comment by KyleBing** [comment]
默认情况下，是读取的程序默认目录，如果安装的不是默认目录，需要自己拖动指定词库目录。在第一个菜单项中指定。

**Comment by chengyi** [comment]
![图片](https://user-images.githubusercontent.com/6308364/140021788-f2e3d598-f5ec-4dad-8e71-725e4149037a.png)
就是默认的，菜单项的打开配置目录也可以正确打开，奇怪

**Comment by KyleBing** [comment]
是由于词库的换行符跟系统换行符不同造成的，通过第三方编辑器，把换行符换成对应系统的换行符就好了。
- macOS 是 LF
- Windows 是 CRLF

**Comment by chengyi** [comment]
解决了， 可以考虑在程序中判断一下 tks
