### ISSUE TITLE
在mac Monterey 12.2.1下无法打开五笔助手

### ISSUE THREAD

**Issue by ansonliao** [KyleBing/wubi-dict-editor#16]
在mac Monterey 12.2.1下无法打开五笔助手，同时五笔助手应用有无法运行的标志。

<img width="100" alt="image" src="https://user-images.githubusercontent.com/6060224/156868656-82443b08-ea0b-4eec-b135-1ae8e2892cdc.png">
<img width="251" alt="image" src="https://user-images.githubusercontent.com/6060224/156868663-a71d451b-adcc-4f15-a1ac-f29e78ff52c3.png">
<img width="579" alt="image" src="https://user-images.githubusercontent.com/6060224/156868681-59527b84-3127-4c79-b71f-1d0028f9ba09.png">

**Comment by KyleBing** [comment]
下前一个版本的  这是arm版的  M1系列处理器的版本   下之前的就好了

**Comment by ansonliao** [comment]
@KyleBing 
好的，我试试。

**Comment by ansonliao** [comment]
@KyleBing 
版本1.1.0 在intel CPU可以使用，谢谢！
