### ISSUE TITLE
能否构建intel版本（mac）的安装包

### ISSUE THREAD

**Issue by qq420100523** [KyleBing/wubi-dict-editor#18]
最新版本没有intel版本的安装包，作者能否构建一下

**Comment by KyleBing** [comment]
我这没环境，可以自己下源码生成一下。


| |
邴新科
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2022年8月2日 13:50 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> |
| 主题 | [KyleBing/wubi-dict-editor] 能否构建intel版本（mac）的安装包 (Issue #18) |

最新版本没有intel版本的安装包，作者能否构建一下

**Comment by songxing10000** [comment]
> 我这没环境，可以自己下源码生成一下。

我是intel的，但是昨天npm run package一直报错，就放弃了

**Comment by KyleBing** [comment]
electron 下载需要走国外的网，如果没有代理，是下不成功的。

**Comment by KyleBing** [comment]
你们有兴趣搞一搞的，我可以提供代理工具。联系我QQ 810656237

**Comment by KyleBing** [comment]
https://github.com/KyleBing/wubi-dict-editor/releases/tag/v1.14
