### ISSUE TITLE
npm run package 依赖找不到

### ISSUE THREAD

**Issue by karzanOnline** [KyleBing/wubi-dict-editor#19]
![image](https://user-images.githubusercontent.com/16421478/196119235-888f19e1-d8cd-4dfb-98ae-e7200a898104.png)

node: v18.4.0

**Comment by karzanOnline** [comment]
这个是打包的时候出现的，相当于说 npm run start 本地跑的时候没问题，当 npm run package 的时候打包出来的 ../node_modules 下依赖不会被打入进去。没看懂为啥，我这边有这个问题，装了一下你的这个项目也有

**Comment by KyleBing** [comment]
run package 的过程中，它应该是会直接去外网下载一些东西的，而这些非 npm 的部分就没有像 taobao tencent 这些镜像源，所以就非常慢，10-20kb/s 过慢或没有速度，就会因超时或无法连接而无法运行。多半会提示网络错误。

最好找个可以代理网络的东西。就不会有类似的问题了。

**Comment by KyleBing** [comment]
看你的错误提示的话，好像不是这个问题，可以试试清空 node_modules 重新部署试试。

**Comment by KyleBing** [comment]
嗯，装这个得用原地址。
