### ISSUE TITLE
macos 12.2.1  无法启动

### ISSUE THREAD

**Issue by chenjia6605** [KyleBing/wubi-dict-editor#20]
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               五笔助手 [10664]
Path:                  /Applications/五笔助手.app/Contents/MacOS/五笔助手
Identifier:            com.electron.
Version:               1.1.4 (1.1.4)
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2022-11-04 16:39:22.6203 +0800
OS Version:            macOS 12.2.1 (21D62)
Report Version:        12
Anonymous UUID:        8ACD3CDD-5A64-1433-5AA3-3E258D7D843B

Time Awake Since Boot: 20000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: @rpath/Electron Framework.framework/Electron Framework
Referenced from: /Applications/五笔助手.app/Contents/MacOS/五笔助手
Reason: tried: '/Applications/五笔助手.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework' (not a mach-o file), '/Applications/五笔助手.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework' (not a mach-o file), '/Library/Frameworks/Electron Framework.framework/Electron Framework' (no such file), '/System/Library/Frameworks/Electron Framework.framework/Electron Framework' (no such file)
(terminated at launch; ignore backtrace)

Application Specific Information:
Library not loaded: @rpath/Electron Framework.framework/Electron Framework
Referenced from: /Applications/五笔助手.app/Contents/MacOS/五笔助手
Reason: tried: '/Applications/五笔助手.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework' (not a mach-o file), '/Applications/五笔助手.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework' (not a mach-o file), '/Library/Frameworks/Electron Framework.framework/Electron Framework' (no such file), '/System/Library/Frameworks/Electron Framework.framework/Electron Framework' (no such file)

Thread 0 Crashed:
0   dyld                          	       0x10387c0ce __abort_with_payload + 10
1   dyld                          	       0x1038921cf abort_with_payload_wrapper_internal + 80
2   dyld                          	       0x103892201 abort_with_payload + 9
3   dyld                          	       0x103840613 dyld4::halt(char const*) + 375
4   dyld                          	       0x10383c55d dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 3955
5   dyld                          	       0x10383b4b4 start + 388

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000002000209  rbx: 0x0000000000000000  rcx: 0x00007ff7be23efb8  rdx: 0x00007ff7be23f420
  rdi: 0x0000000000000006  rsi: 0x0000000000000001  rbp: 0x00007ff7be23f000  rsp: 0x00007ff7be23efb8
   r8: 0x00007ff7be23f020   r9: 0x0000000000000000  r10: 0x0000000000000086  r11: 0x0000000000000246
  r12: 0x0000000000000086  r13: 0x00007ff7be23f420  r14: 0x0000000000000001  r15: 0x0000000000000006
  rip: 0x000000010387c0ce  rfl: 0x0000000000000246  cr2: 0x0000000103842e3c
  
Logical CPU:     0
Error Code:      0x02000209 
Trap Number:     133

Binary Images:
       0x103836000 -        0x1038a1fff dyld (*) <7de33963-bbc5-3996-ba6e-f1d562c17c95> /usr/lib/dyld

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=956K resident=0K(0%) swapped_out_or_unallocated=956K(100%)
Writable regions: Total=9220K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=9220K(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8192K        1 
VM_ALLOCATE                         12K        3 
__DATA                              32K        2 
__DATA_CONST                        80K        1 
__LINKEDIT                         216K        3 
__TEXT                             752K        2 
dyld private memory               1024K        1 
===========                     =======  ======= 
TOTAL                             66.1M       14 

-----------
Full Report
-----------

{"app_name":"五笔助手","timestamp":"2022-11-04 16:39:22.00 +0800","app_version":"1.1.4","slice_uuid":"ab3cb5d1-eb3f-388f-8c63-416a00da1aaa","build_version":"1.1.4","platform":1,"bundleID":"com.electron.","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 12.2.1 (21D62)","incident_id":"40B84205-DE13-4D0A-9D34-D36BE6FC724F","name":"五笔助手"}
{
  "uptime" : 20000,
  "procLaunch" : "2022-11-04 16:39:22.6132 +0800",
  "procRole" : "Default",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "iMac18,3",
  "procStartAbsTime" : 20360253933182,
  "coalitionID" : 3979,
  "osVersion" : {
    "train" : "macOS 12.2.1",
    "build" : "21D62",
    "releaseType" : "User"
  },
  "captureTime" : "2022-11-04 16:39:22.6203 +0800",
  "incident" : "40B84205-DE13-4D0A-9D34-D36BE6FC724F",
  "bug_type" : "309",
  "pid" : 10664,
  "procExitAbsTime" : 20360260562209,
  "cpuType" : "X86-64",
  "procName" : "五笔助手",
  "procPath" : "\/Applications\/五笔助手.app\/Contents\/MacOS\/五笔助手",
  "bundleInfo" : {"CFBundleShortVersionString":"1.1.4","CFBundleVersion":"1.1.4","CFBundleIdentifier":"com.electron."},
  "storeInfo" : {"deviceIdentifierForVendor":"720E3CD8-CD5A-57CC-9029-8C393755CCF4","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.electron.",
  "crashReporterKey" : "8ACD3CDD-5A64-1433-5AA3-3E258D7D843B",
  "sip" : "enabled",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"code":1,"flags":518,"namespace":"DYLD","indicator":"Library missing","details":["(terminated at launch; ignore backtrace)"],"reasons":["Library not loaded: @rpath\/Electron Framework.framework\/Electron Framework","Referenced from: \/Applications\/五笔助手.app\/Contents\/MacOS\/五笔助手","Reason: tried: '\/Applications\/五笔助手.app\/Contents\/MacOS\/..\/Frameworks\/Electron Framework.framework\/Electron Framework' (not a mach-o file), '\/Applications\/五笔助手.app\/Contents\/MacOS\/..\/Frameworks\/Electron Framework.framework\/Electron Framework' (not a mach-o file), '\/Library\/Frameworks\/Electron Framework.framework\/Electron Framework' (no such file), '\/System\/Library\/Frameworks\/Electron Framework.framework\/Electron Framework' (no such file)"]},
  "asi" : {"dyld":["Library not loaded: @rpath\/Electron Framework.framework\/Electron Framework","Referenced from: \/Applications\/五笔助手.app\/Contents\/MacOS\/五笔助手","Reason: tried: '\/Applications\/五笔助手.app\/Contents\/MacOS\/..\/Frameworks\/Electron Framework.framework\/Electron Framework' (not a mach-o file), '\/Applications\/五笔助手.app\/Contents\/MacOS\/..\/Frameworks\/Electron Framework.framework\/Electron Framework' (not a mach-o file), '\/Library\/Frameworks\/Electron Framework.framework\/Electron Framework' (no such file), '\/System\/Library\/Frameworks\/Electron Framework.framework\/Electron Framework' (no such file)"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":259457,"threadState":{"r13":{"value":140702023676960},"rax":{"value":33554953},"rflags":{"value":582},"cpu":{"value":0},"r14":{"value":1},"rsi":{"value":1},"r8":{"value":140702023675936},"cr2":{"value":4353961532},"rdx":{"value":140702023676960},"r10":{"value":134},"r9":{"value":0},"r15":{"value":6},"rbx":{"value":0},"trap":{"value":133},"err":{"value":33554953},"r11":{"value":582},"rip":{"value":4354195662,"matchesCrashFrame":1},"rbp":{"value":140702023675904},"rsp":{"value":140702023675832},"r12":{"value":134},"rcx":{"value":140702023675832},"flavor":"x86_THREAD_STATE","rdi":{"value":6}},"frames":[{"imageOffset":286926,"symbol":"__abort_with_payload","symbolLocation":10,"imageIndex":0},{"imageOffset":377295,"symbol":"abort_with_payload_wrapper_internal","symbolLocation":80,"imageIndex":0},{"imageOffset":377345,"symbol":"abort_with_payload","symbolLocation":9,"imageIndex":0},{"imageOffset":42515,"symbol":"dyld4::halt(char const*)","symbolLocation":375,"imageIndex":0},{"imageOffset":25949,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":3955,"imageIndex":0},{"imageOffset":21684,"symbol":"start","symbolLocation":388,"imageIndex":0}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4353908736,
    "size" : 442368,
    "uuid" : "7de33963-bbc5-3996-ba6e-f1d562c17c95",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  }
],
  "sharedCache" : {
  "base" : 140703651799040,
  "size" : 15216836608,
  "uuid" : "0939015d-8308-3e69-b095-bd928f835202"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=956K resident=0K(0%) swapped_out_or_unallocated=956K(100%)\nWritable regions: Total=9220K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=9220K(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nSTACK GUARD                       56.0M        1 \nStack                             8192K        1 \nVM_ALLOCATE                         12K        3 \n__DATA                              32K        2 \n__DATA_CONST                        80K        1 \n__LINKEDIT                         216K        3 \n__TEXT                             752K        2 \ndyld private memory               1024K        1 \n===========                     =======  ======= \nTOTAL                             66.1M       14 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "607844aa04477260f58a8077",
      "factorPackIds" : {
        "SIRI_MORPHUN_ASSETS" : "6103050cbfe6dc472e1c982a"
      },
      "deploymentId" : 240000066
    },
    {
      "rolloutId" : "60da5e84ab0ca017dace9abf",
      "factorPackIds" : {

      },
      "deploymentId" : 240000008
    },
    {
      "rolloutId" : "602ad4dac86151000cf27e46",
      "factorPackIds" : {
        "SIRI_DICTATION_ASSETS" : "6193d03f2171a2330e561dfc"
      },
      "deploymentId" : 240000305
    },
    {
      "rolloutId" : "601d9415f79519000ccd4b69",
      "factorPackIds" : {
        "SIRI_TEXT_TO_SPEECH" : "622657ce37186c771d5404ad"
      },
      "deploymentId" : 240000416
    },
    {
      "rolloutId" : "5fb4245a1bbfe8005e33a1e1",
      "factorPackIds" : {

      },
      "deploymentId" : 240000015
    },
    {
      "rolloutId" : "60186475825c62000ccf5450",
      "factorPackIds" : {

      },
      "deploymentId" : 240000026
    },
    {
      "rolloutId" : "60f8ddccefea4203d95cbeef",
      "factorPackIds" : {

      },
      "deploymentId" : 240000021
    },
    {
      "rolloutId" : "5ffde50ce2aacd000d47a95f",
      "factorPackIds" : {

      },
      "deploymentId" : 240000211
    },
    {
      "rolloutId" : "63582c5f8a53461413999550",
      "factorPackIds" : {

      },
      "deploymentId" : 240000001
    },
    {
      "rolloutId" : "5fc94383418129005b4e9ae0",
      "factorPackIds" : {

      },
      "deploymentId" : 240000529
    }
  ],
  "experiments" : [

  ]
}
}

Model: iMac18,3, BootROM 447.80.3.0.0, 4 processors, Quad-Core Intel Core i7, 4.2 GHz, 32 GB, SMC 2.41f2
Graphics: Radeon Pro 575, Radeon Pro 575, PCIe, 4 GB
Display: iMac, Retina 5K (5120 x 2880), Main, MirrorOff, Online
Memory Module: BANK 0/DIMM0, 16 GB, DDR4 SO-DIMM, 2400 MHz, 0x80AD, 0x484D4138324753364D4652384E2D554820202020
Memory Module: BANK 1/DIMM0, 16 GB, DDR4 SO-DIMM, 2400 MHz, 0x80AD, 0x484D4138324753364D4652384E2D554820202020
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x16F), Broadcom BCM43xx 1.0 (7.77.111.1 AirPortDriverBrcmNIC-1710.3)
AirPort: 
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
USB Device: USB30Bus
USB Device: Bluetooth USB Host Controller
USB Device: FaceTime HD Camera (Built-in)
Thunderbolt Bus: iMac, Apple Inc., 41.5

**Comment by KyleBing** [comment]
试试这个： 
[https://github.com/KyleBing/wubi-dict-editor/releases/download/v1.14/wubi-dict-editor-macOS-1.1.4-macOS-Intel-x64.dmg](https://github.com/KyleBing/wubi-dict-editor/releases/download/v1.14/wubi-dict-editor-macOS-1.1.4-macOS-Intel-x64.dmg)

**Comment by chenjia6605** [comment]
使用上述包，运行成功
