### ISSUE TITLE
macos13.0.1 M1无法打开app

### ISSUE THREAD

**Issue by xiewl** [KyleBing/wubi-dict-editor#21]
两个dmg包都试了，都打不开
<img width="280" alt="Snipaste_2023-01-09_16-43-34" src="https://user-images.githubusercontent.com/15881722/211268970-b0a63b06-a53a-470c-b831-6ed6e3ff57fb.png">

<img width="260" alt="Snipaste_2023-01-09_16-44-25" src="https://user-images.githubusercontent.com/15881722/211269168-f98dee34-58a9-4015-aeae-141a6c62d3f1.png">

**Comment by KyleBing** [comment]
可以百度一下这种情况，经常见

**Comment by KyleBing** [comment]
http://www.winwin7.com/JC/22173.html

**Comment by xiewl** [comment]
不过我刚刚clone源码下来，手动make的app能正常打开了。

**Comment by KyleBing** [comment]
M1 arm 就是的

**Comment by xiewl** [comment]
好吧，能用就行了。感谢

**Comment by xiewl** [comment]
@KyleBing  最后请问一下，kylebing的邀请码在哪里获取呢。

**Comment by KyleBing** [comment]
发我你的邮箱吧， 我发你，近段时间因恶意注册，所以把它去了。

**Comment by xiewl** [comment]
> 

wndwl@qq.com   感谢

**Comment by JiandanDream** [comment]
打不开 arm 的包，报一样的错误，但 intel 的包能正常使用。
版本 v1.18
电脑系统 13.2.1 (22D68) M1
