### ISSUE TITLE
邀请码

### ISSUE THREAD

**Issue by louis2610** [KyleBing/wubi-dict-editor#23]
大佬，邀请码怎么获取呢？

**Comment by KyleBing** [comment]
给我发邮件索取即可  kylebing@163.com

**Comment by louis2610** [comment]
你好，邀请码能给一下吗？谢谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "KyleBing/wubi-dict-editor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月10日(星期五) 下午2:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [KyleBing/wubi-dict-editor] 邀请码 (Issue #23)





 
给我发邮件索取即可  ***@***.***

**Comment by KyleBing** [comment]
兄弟你这么有毅力吗，好久没看 issue，我以为你早就放弃了


欢迎使用：
Z3I7b8+nU7tuNu0G
邀请码有效期：3天


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年11月10日 14:20 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [KyleBing/wubi-dict-editor] 邀请码 (Issue #23) |

你好，邀请码能给一下吗？谢谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "KyleBing/wubi-dict-editor" ***@***.***&gt;;
发送时间:&nbsp;2023年11月10日(星期五) 下午2:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [KyleBing/wubi-dict-editor] 邀请码 (Issue #23)






给我发邮件索取即可 ***@***.***

**Comment by louis2610** [comment]
我是忠实的五笔用户，也不可能改别的输入法，也刚好看的你回复的邮件，哈哈




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "KyleBing/wubi-dict-editor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月10日(星期五) 下午2:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [KyleBing/wubi-dict-editor] 邀请码 (Issue #23)





 兄弟你这么有毅力吗，好久没看 issue，我以为你早就放弃了
 
 
 欢迎使用：
 Z3I7b8+nU7tuNu0G
 邀请码有效期：3天
 
 
 ---- 回复的原邮件 ----
 | 发件人 | ***@***.***&gt; |
 | 发送日期 | 2023年11月10日 14:20 |
 | 收件人 | ***@***.***&gt; |
 | 抄送人 | ***@***.***&gt; ,
 ***@***.***&gt; |
 | 主题 | Re: [KyleBing/wubi-dict-editor] 邀请码 (Issue #23) |
 
 你好，邀请码能给一下吗？谢谢！
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------
 发件人: "KyleBing/wubi-dict-editor" ***@***.***&amp;gt;;
 发送时间:&amp;nbsp;2023年11月10日(星期五) 下午2:11
 ***@***.***&amp;gt;;
 ***@***.******@***.***&amp;gt;;
 主题:&amp;nbsp;Re: [KyleBing/wubi-dict-editor] 邀请码 (Issue #23)
 
 
 
 
 
 
 给我发邮件索取即可 ***@***.***
