### ISSUE TITLE
增加下级文件夹中词库文件的查找

### ISSUE THREAD

**Issue by hsingll** [KyleBing/wubi-dict-editor#24]
~/Library/Rime下很多配置文件，当词库文件继续增加时，会显得很乱，所以可以新建文件夹单独放置词库。
希望能增加对下级文件夹中词库文件的查找。

**Comment by KyleBing** [comment]
这是输入法的功能建议，可以到输入法的仓库中建议。这里只是一个输入法的工具。

[https://github.com/rime](https://github.com/rime)

**Comment by hsingll** [comment]
> 这是输入法的功能建议，可以到输入法的仓库中建议。这里只是一个输入法的工具。
> 
> https://github.com/rime

不好意思，我可能没有表达完全。
输入法是支持这样的，但是词库工具不支持，所以我每次得把词从下级文件夹移到~/Library/Rime里，词库工具才能识别到词库文件，然后编辑完我还得挪回去。

并且其他输入方案的词库也会显示在词库工具的列表里，只是读不出内容。

我想，直接读取wubi86_jidian.schema.yaml里主词库的路径后再继续遍历主词库包含的其他词库的路径直到找到所有的五笔词库文件路径，再展示会不会更好点。

如下是我主词库的配置，将其他词库移到了dicts文件夹中。
```yaml
import_tables: # 此处是添加用户自定义词库的地方
  - dicts/wubi86_jidian_user                # 个人私有词库
  - dicts/wubi86_jidian_extra               # 扩展词库
```

**Comment by KyleBing** [comment]
可以先用给码表命名别名的方式使用 
<img width="912" alt="Screenshot 2023-09-01 at 23 22 06" src="https://github.com/KyleBing/wubi-dict-editor/assets/12215982/6991b9a2-c52c-4ea8-9515-e902d250a729">
