### ISSUE TITLE
是否支持Windows11自带的微软五笔？

### ISSUE THREAD

**Issue by Ressler-Git** [KyleBing/wubi-dict-editor#26]
麻烦请教一下这个词库是否支持Windows11自带的微软五笔？或者说是否可以通过什么方式转换然后替换微软五笔的码表，我目前只知道可以使用.lex格式的词库。
感谢。

**Comment by KyleBing** [comment]
https://github.com/aardio/wubi-lex 这个好像可以操作 微软输入法，估计可以将本库码表处理成 lex，可以试试看。这个目前没有对应的直接可用的 lex 词库。
