### ISSUE TITLE
是不支持mac m1吗？

### ISSUE THREAD

**Issue by leoxml** [KyleBing/wubi-dict-editor#32]
<img width="703" alt="image" src="https://github.com/user-attachments/assets/5f6dabf5-7c86-4c22-a34e-a0f6720dd912">

**Comment by KyleBing** [comment]
支持   直接百度搜 “已损坏，无法打开”这个错误，就能找到解决办法。

**Comment by nohzafk** [comment]
打开 " 终端 " 执行如下命令（根据提示输入您的密码即可）：

> sudo xattr -dr com.apple.quarantine /Applications/五笔码表助手.app

不清楚以下命令是否有用

> sudo spctl --master-disable
