### ISSUE TITLE
首次打开后报错

### ISSUE THREAD

**Issue by bosconb** [KyleBing/wubi-dict-editor#4]
系统：Big Sur 11.4

![Xnip2021-08-09_17-12-09](https://user-images.githubusercontent.com/47100031/128683925-08d114bb-2db4-40a1-82a4-f963fc8a06c0.jpg)

确认窗口警告后可运行，但每次关闭程序再度打开后仍会出现。

**Comment by KyleBing** [comment]
嗯，这个没事，下版已修正。

**Comment by KyleBing** [comment]
可以下载试用最新版 
[https://github.com/KyleBing/wubi-dict-editor/releases/tag/v1.01beta2](https://github.com/KyleBing/wubi-dict-editor/releases/tag/v1.01beta2)
